# Config file for fcnet_train15 experiment
exp_name: emb_nnet_train08-15_aux
model: emb
epochs: 50
lr: 0.005
verbose: 1
batch_size: 4096
hidden_nodes: 1000
use_aux: True
emb_size: 2
train_dates: 2008-01-01 2016-01-01
validation_split: 0.2
es_patience: 2
pickled_sets: aux_08-15_16.pkl