exp_name: emb_nnet_train08-15_aux
model: emb
epochs: 50
lr: 0.002
verbose: 1
batch_size: 4096
hidden_nodes: 500
use_aux: True
emb_size: 2
train_dates: [2008-01-01, 2016-01-01]
validation_split: 0.2
es_patience: 2
add_current_error: True
current_error_len: 30
pickled_sets: aux_08-15_16_current30.pkl