# Config file for fcnet_train15 experiment
exp_name: nnet_train08-15_aux
model: hidden
epochs: 50
lr: 0.005
verbose: 1
hidden_nodes: 500
batch_size: 4096
use_aux: True
train_dates: 2008-01-01 2016-01-01
validation_split: 0.2
es_patience: 2